#!/usr/bin/env python3
"""
Auto-updater for DATA.md (Team 18833 - Megiddo Lions).

Scrapes FIRST's official FTC event pages for every season the team played
(rookie year -> current) and rewrites the auto-generated block in DATA.md
(between the BEGIN/END LIVE TEAM DATA markers).

Usage:
    python3 update_team_data.py           # update DATA.md
    python3 update_team_data.py --check   # show what would change, write nothing
    python3 update_team_data.py --team 18833 --data-file DATA.md

No third-party dependencies (stdlib only). GitHub Actions runs this weekly;
see .github/workflows/update-data.yml.
"""

import argparse
import difflib
import re
import sys
import urllib.error
import urllib.request
from datetime import datetime, timezone
from html import unescape

TEAM_NUMBER = 18833
DATA_FILE = "DATA.md"
FIRST_URL = "https://ftc-events.firstinspires.org/{season}/team/{team}"
FIRST_SEASON = 2020  # fallback lower bound; real rookie year is read from FIRST
ROOKIE_YEAR_OVERRIDE = 2019  # shown instead of FIRST's 2020 (team active in 2019–20 SKYSTONE)
HEADERS = {"User-Agent": "Mozilla/5.0 (compatible; team18833-data-updater/1.0)"}

BEGIN_MARK = "<!-- BEGIN LIVE TEAM DATA (generated by update_team_data.py — do not edit) -->"
END_MARK = "<!-- END LIVE TEAM DATA (generated by update_team_data.py — do not edit) -->"

DATE_RE = re.compile(r"^[A-Z][a-z]+ \d{1,2} to [A-Z][a-z]+ \d{1,2}, \d{4}$")
RANK_RE = re.compile(r"^Rank: (\d+) of (\d+)$")
RANK_VALUE_RE = re.compile(r"^(\d+) of (\d+)$")
# Footer/nav junk that must end awards-table parsing on sparse pages.
FOOTER_STOP = {"About", "Contact Us", "Donate", "Privacy Policy", "Legal Notices",
               "Report a Concern", "FIRST Store", "API / Services", "Home", "Events",
               "Teams", "Insights", "Watch", "Add Data", "Open Source", "Team Summary",
               "All Events", "Awards"}


def fetch(url: str) -> str:
    req = urllib.request.Request(url, headers=HEADERS)
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read().decode("utf-8", "replace")


def html_to_lines(html: str) -> list:
    html = re.sub(r"<(script|style)\b[^>]*>.*?</\1>", " ", html, flags=re.S | re.I)
    text = re.sub(r"<[^>]+>", "\n", html)
    text = unescape(text)
    lines = [ln.strip() for ln in text.splitlines()]
    return [ln for ln in lines if ln]


def parse_season_page(html: str) -> dict:
    """Parse one FIRST season page for the team into a dict."""
    lines = html_to_lines(html)
    text = "\n".join(lines)

    data = {"page_season": None, "name": None, "summary": {},
            "record": None, "events": [], "awards": []}

    m = re.search(rf"^Team {TEAM_NUMBER} - (.+?) \((20\d{{2}})\)$", text, re.M)
    if not m:
        return data
    data["name"], data["page_season"] = m.group(1), int(m.group(2))

    for sm in re.finditer(r"^(20\d{2}): (.+)$", text, re.M):
        data["summary"][sm.group(1)] = sm.group(2)

    rec = re.search(r"had a record of\s*(\d+)\s*-\s*(\d+)\s*-\s*(\d+)", text)
    qual = re.search(r"Qualification record of\s*(\d+)\s*-\s*(\d+)\s*-\s*(\d+)", text)
    playoff = re.search(r"Playoff record of\s*(\d+)\s*-\s*(\d+)\s*-\s*(\d+)", text)
    n_events = re.search(r"at their (\d+) official events", text)
    if rec:
        data["record"] = {
            "w": rec.group(1), "l": rec.group(2), "t": rec.group(3),
            "qual": "-".join(qual.groups()) if qual else None,
            "playoff": "-".join(playoff.groups()) if playoff else None,
            "events": n_events.group(1) if n_events else None,
        }

    seen_events, seen_awards = set(), set()
    current_event = None
    i = 0
    while i < len(lines):
        ln = lines[i]
        if DATE_RE.match(ln) and i > 0:
            current_event = lines[i - 1]
        rank = RANK_RE.match(ln)
        if not rank and ln == "Rank:" and i + 1 < len(lines):
            vm = RANK_VALUE_RE.match(lines[i + 1])
            if vm:
                rank = vm  # "Rank:" and "N of M" arrive as separate lines
        if rank and current_event:
            key = (current_event, rank.group(1), rank.group(2))
            if key not in seen_events:
                seen_events.add(key)
                data["events"].append({
                    "name": current_event,
                    "rank": int(rank.group(1)),
                    "of": int(rank.group(2)),
                })
        if re.search(rf"^Team {TEAM_NUMBER}'s (20\d{{2}}) Awards$", ln):
            j = i + 1
            if j + 1 < len(lines) and lines[j] == "Award" and lines[j + 1] == "Event":
                j += 2
                while j + 1 < len(lines) and not DATE_RE.match(lines[j + 1]):
                    award_name = re.sub(r"\s+", " ", lines[j])
                    award_event = re.sub(r"\s+", " ", lines[j + 1])
                    if award_name in FOOTER_STOP or award_name.startswith("©") \
                            or award_event in FOOTER_STOP or award_event.startswith("©"):
                        break
                    award = (award_name, award_event)
                    if award not in seen_awards:
                        seen_awards.add(award)
                        data["awards"].append({"name": award_name, "event": award_event})
                    j += 2
                i = j
        i += 1
    return data


def parse_identity(html: str) -> dict:
    text = "\n".join(html_to_lines(html))
    identity = {}
    m = re.search(r"^From:\s*(.+)$", text, re.M)
    identity["Location"] = m.group(1).strip() if m else None
    m = re.search(r"^Region:\s*(.+)$", text, re.M)
    identity["Region"] = m.group(1).strip() if m else None
    m = re.search(r"^Rookie Year:\s*(\d{4})$", text, re.M)
    # FIRST lists 2020 (no official 2019–20 SKYSTONE events), but the team was
    # already building and operating in 2019 — display 2019 everywhere.
    identity["Rookie year"] = str(ROOKIE_YEAR_OVERRIDE)
    m = re.search(r"^(20\d{2}) Sponsors:\s*(.*)$", text, re.M)
    if m:
        sponsor = m.group(2).strip()
        if not sponsor:  # value sits on the next line in FIRST's markup
            nxt = text[m.end():].lstrip().splitlines()
            sponsor = nxt[0].strip() if nxt else ""
        # FIRST has no separate organization field; its sponsor line is the
        # school/org. Stored as Organization only — the Sponsors row was
        # removed from the site and DATA.md.
        identity["Organization"] = sponsor or None
    else:
        identity["Organization"] = None
    loc = identity.get("Location") or ""
    identity["Country"] = loc.split(",")[-1].strip() if "," in loc else loc
    return identity


def merge_identity(base: dict, extra: dict) -> dict:
    """Fill missing identity fields (e.g. the preseason page has no sponsor line)."""
    merged = dict(base)
    for key, value in extra.items():
        if not merged.get(key) and value:
            merged[key] = value
    return merged


def collect() -> tuple:
    """Fetch every season page from now back to the rookie year."""
    start_year = datetime.now(timezone.utc).year
    seasons, identity, rookie_year, name = [], None, None, None
    season = start_year
    consecutive_misses = 0
    while season >= FIRST_SEASON:
        if rookie_year is not None and season < int(rookie_year):
            break
        try:
            html = fetch(FIRST_URL.format(season=season, team=TEAM_NUMBER))
        except urllib.error.HTTPError as err:
            if err.code in (404, 410):
                season -= 1
                continue
            raise
        parsed = parse_season_page(html)
        if parsed["name"] is None:
            consecutive_misses += 1
            if consecutive_misses >= 2 and not seasons:
                sys.exit(f"ERROR: could not find team {TEAM_NUMBER} on FIRST's site.")
            season -= 1
            continue
        consecutive_misses = 0
        page_season = parsed["page_season"] or season
        if identity is None:
            identity = parse_identity(html)
            rookie_year = identity["Rookie year"]
        else:
            identity = merge_identity(identity, parse_identity(html))
        name = parsed["name"]
        has_activity = bool(parsed["record"] or parsed["events"] or parsed["awards"])
        seasons.append({"season": page_season,
                        "game": parsed["summary"].get(str(page_season)),
                        "active": has_activity,
                        **{k: parsed[k] for k in ("record", "events", "awards")}})
        season -= 1
    if not seasons:
        sys.exit(f"ERROR: no season pages found for team {TEAM_NUMBER}.")
    seasons.sort(key=lambda s: s["season"], reverse=True)
    return name, identity, seasons


def render_block(name: str, identity: dict, seasons: list) -> str:
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    # Only seasons with real activity (events/awards/record) are listed;
    # pre-season pages with nothing scheduled are skipped.
    seasons = [s for s in seasons if s["active"]]
    if not seasons:
        sys.exit(f"ERROR: no seasons with events found for team {TEAM_NUMBER}.")
    current = seasons[0]
    lines = [
        BEGIN_MARK,
        "",
        "### Team identity",
        f"Number: {TEAM_NUMBER}",
        f"Name: {name}",
        f"Organization: {identity.get('Organization') or '-'}",
        f"Location: {identity.get('Location') or '-'}",
        f"Country: {identity.get('Country') or '-'}",
        f"Region: {identity.get('Region') or '-'}",
        f"Rookie year: {identity.get('Rookie year') or '-'}",
        f"Current season: {current['season']}",
        f"Current season name: {current['game']}",
        f"Data updated: {today}",
        "",
        "### Season history",
    ]
    for s in seasons:
        lines.append(f"#### {s['season']} — {s['game'] or '?'}")
        rec = s["record"]
        if rec:
            extra = []
            if rec.get("qual"):
                extra.append(f"qualification {rec['qual']}")
            if rec.get("playoff"):
                extra.append(f"playoffs {rec['playoff']}")
            detail = f" ({', '.join(extra)})" if extra else ""
            n = f" at {rec['events']} official events" if rec.get("events") else ""
            lines.append(f"Record: {rec['w']}-{rec['l']}-{rec['t']}{detail}{n}")
        else:
            lines.append("Record: no official events")
        if not s["events"]:
            lines.append("Events: none")
        for ev in s["events"]:
            lines.append(f"Event: {ev['name']} — quals rank {ev['rank']} of {ev['of']}")
        if not s["awards"]:
            lines.append("Awards: none")
        for aw in s["awards"]:
            lines.append(f"Award: {aw['name']} — {aw['event']}")
        lines.append("")
    lines.append(END_MARK)
    return "\n".join(lines)


def replace_block(markdown: str, new_block: str) -> str:
    pattern = re.compile(re.escape(BEGIN_MARK) + r".*?" + re.escape(END_MARK), re.S)
    if not pattern.search(markdown):
        sys.exit(f"ERROR: {DATA_FILE} is missing the {BEGIN_MARK} marker block.")
    return pattern.sub(lambda _m: new_block, markdown, count=1)


def main() -> None:
    global TEAM_NUMBER, DATA_FILE

    ap = argparse.ArgumentParser(description="Auto-update DATA.md for FTC team 18833")
    ap.add_argument("--team", type=int, default=TEAM_NUMBER)
    ap.add_argument("--data-file", default=DATA_FILE)
    ap.add_argument("--check", action="store_true", help="show diff only, do not write")
    args = ap.parse_args()

    TEAM_NUMBER, DATA_FILE = args.team, args.data_file

    name, identity, seasons = collect()
    new_block = render_block(name, identity, seasons)

    with open(DATA_FILE, encoding="utf-8") as fh:
        markdown = fh.read()

    old_block = re.search(re.escape(BEGIN_MARK) + r".*?" + re.escape(END_MARK), markdown, re.S)
    old_block = old_block.group(0) if old_block else ""

    if args.check:
        if old_block == new_block:
            print("DATA.md is up to date.")
        else:
            diff = difflib.unified_diff(old_block.splitlines(), new_block.splitlines(),
                                        "DATA.md (current)", "DATA.md (fresh)", lineterm="")
            print("\n".join(diff))
        return

    with open(DATA_FILE, "w", encoding="utf-8") as fh:
        fh.write(replace_block(markdown, new_block))
    print(f"Updated {DATA_FILE}: {len(seasons)} seasons, "
          f"current season {seasons[0]['season']} ({seasons[0]['game']}).")


if __name__ == "__main__":
    main()
